version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "npm"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "npm(website)"

  - package-ecosystem: "docker"
    directory: "/website"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker(website)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "ci"
